# Generated by Django 3.0.5 on 2020-07-11 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Required',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityrequired', models.IntegerField(default=1)),
                ('increment', models.BooleanField(default=False)),
                ('partsrequired', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for_jobs', to='parts.PartsList')),
                ('reqid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_orders.Jobs')),
            ],
        ),
    ]
