# Generated by Django 3.0.5 on 2020-07-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0002_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='quantitycompleted',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='quantityrequired',
            field=models.IntegerField(),
        ),
    ]
