# Generated by Django 3.0.5 on 2020-07-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0003_auto_20200711_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
