# Generated by Django 3.0.3 on 2020-07-16 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_orders', '0004_activitylog_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityid', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityRequiredParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityrequired', models.IntegerField(default=1)),
                ('increment', models.BooleanField(default=False)),
                ('activityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_orders.Activities')),
                ('partsrequired', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for_jobs', to='parts.PartsList')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('activityid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_orders.Activities')),
            ],
        ),
        migrations.CreateModel(
            name='WorkCentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=50)),
                ('increment', models.BooleanField(default=False)),
                ('quantityrequired', models.IntegerField()),
                ('quantitycompleted', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('activityid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_orders.Activities')),
                ('partsrequired', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parts.PartsList')),
                ('task_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_orders.Tasks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='required',
            name='partsrequired',
        ),
        migrations.RemoveField(
            model_name='required',
            name='reqid',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.DeleteModel(
            name='Required',
        ),
    ]
