# Generated by Django 3.0.3 on 2020-04-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='partslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnumber', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=20)),
                ('supplier', models.CharField(max_length=50)),
                ('stockonhand', models.IntegerField()),
                ('minimumstock', models.IntegerField()),
                ('reorderqtys', models.IntegerField()),
                ('qtyperassembly', models.IntegerField()),
                ('boxsize', models.IntegerField()),
                ('leadtime', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
